behaviors:
  VerticalParkingAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 16
      buffer_size: 1000
      learning_rate: 0.00035
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.75
        strength: 0.99
    max_steps: 100000000
    time_horizon: 64
    summary_freq: 20000
    threaded: true